version: '3'

dotenv: ['.env']

vars:
  BUILD_DIR: .bin
  SOURCE_DIR: .src
  # Ports
  PORT_WRANGLER: 8787
  PORT_WAZERO: 8080
  PORT_DEMO: 3000
  PORT_PC: 9999
  # Test repos (ajstarks)
  DECK_REPO: https://github.com/ajstarks/deck.git
  DECKSH_REPO: https://github.com/ajstarks/decksh.git
  DECKVIZ_REPO: https://github.com/ajstarks/deckviz.git
  DCHART_REPO: https://github.com/ajstarks/dchart.git
  DECKFONTS_REPO: https://github.com/ajstarks/deckfonts.git
  # Cloudflare
  CF_WORKER_NAME: deckfs
  CF_R2_INPUT: deckfs-input
  CF_R2_OUTPUT: deckfs-output
  CF_R2_WASM: deckfs-wasm
  CF_R2_FONTS: deckfs-fonts
  CF_QUEUE: deckfs-events
  CF_KV_NAMESPACE: DECKFS_STATUS

env:
  GOWORK: off
  DECKFONTS: "sans:Helvetica,mono:Courier,serif:Times,symbol:Symbol"

includes:
  build: ./taskfiles/build.yaml
  run: ./taskfiles/run.yaml
  pc: ./taskfiles/pc.yaml
  test: ./taskfiles/test.yaml
  cf: ./taskfiles/cf.yaml
  src: ./taskfiles/src.yaml
  util: ./taskfiles/util.yaml

tasks:
  default:
    cmds: [task --list]
    silent: true

  info:
    desc: Quick start guide
    silent: true
    cmds:
      - |
        echo "DeckFS - decksh to SVG"
        echo ""
        echo "LOCAL DEV:"
        echo "  task run:wrangler  # Cloudflare emulator (:{{.PORT_WRANGLER}})"
        echo ""
        echo "DEPLOY:"
        echo "  task cf:deploy      # Push to Cloudflare"
        echo ""
        echo "See CLAUDE.md for full architecture"
