version: '3'

tasks:
  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}

  cloudflare:
    desc: Build for Cloudflare Workers (TinyGo)
    cmds:
      - mkdir -p {{.BUILD_DIR}}/cloudflare
      - go run github.com/syumai/workers/cmd/workers-assets-gen@latest -o {{.BUILD_DIR}}/cloudflare
      - tinygo build -tags cloudflare -target wasm -no-debug -o {{.BUILD_DIR}}/cloudflare/app.wasm ./cmd/cloudflare
    sources:
      - cmd/cloudflare/**/*.go
      - handler/**/*.go
      - runtime/**/*.go
      - internal/**/*.go
      - go.mod
      - go.sum
    generates:
      - "{{.BUILD_DIR}}/cloudflare/app.wasm"
      - "{{.BUILD_DIR}}/cloudflare/worker.mjs"

  wasi:
    desc: Build WASI module (wazero, wasmtime)
    cmds:
      - mkdir -p {{.BUILD_DIR}}/wasi
      - tinygo build -target wasi -o {{.BUILD_DIR}}/wasi/deckfs.wasm ./cmd/wasi
    sources:
      - cmd/wasi/**/*.go
      - handler/**/*.go
      - runtime/**/*.go
      - internal/**/*.go
      - go.mod
      - go.sum
    generates:
      - "{{.BUILD_DIR}}/wasi/deckfs.wasm"

  host:
    desc: Build wazero host binary
    cmds:
      - mkdir -p {{.BUILD_DIR}}/wazero
      - go build -o {{.BUILD_DIR}}/wazero/deckfs-host ./cmd/wazero
    sources:
      - cmd/wazero/**/*.go
      - handler/**/*.go
      - runtime/**/*.go
      - internal/**/*.go
      - pkg/**/*.go
      - go.mod
      - go.sum
    generates:
      - "{{.BUILD_DIR}}/wazero/deckfs-host"

  cli:
    desc: Build native CLI
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - go build -o {{.BUILD_DIR}}/deckfs ./cmd/cli
    sources:
      - cmd/cli/**/*.go
      - handler/**/*.go
      - runtime/**/*.go
      - internal/**/*.go
      - pkg/**/*.go
      - go.mod
      - go.sum
    generates:
      - "{{.BUILD_DIR}}/deckfs"

  tools:
    desc: Build ajstarks deck CLI binaries from .src (not the deckfs runtime)
    deps: [tools-decksh, tools-dshfmt, tools-dshlint, tools-svgdeck, tools-pngdeck, tools-pdfdeck]

  tools-decksh:
    desc: Build decksh from .src
    dir: "{{.ROOT_DIR}}/{{.SOURCE_DIR}}/decksh/cmd/decksh"
    cmds:
      - mkdir -p {{.ROOT_DIR}}/{{.BUILD_DIR}}/deck
      - go build -o {{.ROOT_DIR}}/{{.BUILD_DIR}}/deck/decksh .
    status:
      - test -f {{.ROOT_DIR}}/{{.BUILD_DIR}}/deck/decksh
    preconditions:
      - test -d {{.ROOT_DIR}}/{{.SOURCE_DIR}}/decksh

  tools-dshfmt:
    desc: Build dshfmt from .src
    dir: "{{.ROOT_DIR}}/{{.SOURCE_DIR}}/decksh/cmd/dshfmt"
    cmds:
      - mkdir -p {{.ROOT_DIR}}/{{.BUILD_DIR}}/deck
      - go build -o {{.ROOT_DIR}}/{{.BUILD_DIR}}/deck/dshfmt .
    status:
      - test -f {{.ROOT_DIR}}/{{.BUILD_DIR}}/deck/dshfmt
    preconditions:
      - test -d {{.ROOT_DIR}}/{{.SOURCE_DIR}}/decksh

  tools-dshlint:
    desc: Build dshlint from .src
    dir: "{{.ROOT_DIR}}/{{.SOURCE_DIR}}/decksh/cmd/dshlint"
    cmds:
      - mkdir -p {{.ROOT_DIR}}/{{.BUILD_DIR}}/deck
      - go build -o {{.ROOT_DIR}}/{{.BUILD_DIR}}/deck/dshlint .
    status:
      - test -f {{.ROOT_DIR}}/{{.BUILD_DIR}}/deck/dshlint
    preconditions:
      - test -d {{.ROOT_DIR}}/{{.SOURCE_DIR}}/decksh

  tools-svgdeck:
    desc: Build svgdeck from .src
    dir: "{{.ROOT_DIR}}/{{.SOURCE_DIR}}/deck/cmd/svgdeck"
    cmds:
      - mkdir -p {{.ROOT_DIR}}/{{.BUILD_DIR}}/deck
      - go build -o {{.ROOT_DIR}}/{{.BUILD_DIR}}/deck/svgdeck .
    status:
      - test -f {{.ROOT_DIR}}/{{.BUILD_DIR}}/deck/svgdeck
    preconditions:
      - test -d {{.ROOT_DIR}}/{{.SOURCE_DIR}}/deck

  tools-pngdeck:
    desc: Build pngdeck from .src
    dir: "{{.ROOT_DIR}}/{{.SOURCE_DIR}}/deck/cmd/pngdeck"
    cmds:
      - mkdir -p {{.ROOT_DIR}}/{{.BUILD_DIR}}/deck
      - go build -o {{.ROOT_DIR}}/{{.BUILD_DIR}}/deck/pngdeck .
    status:
      - test -f {{.ROOT_DIR}}/{{.BUILD_DIR}}/deck/pngdeck
    preconditions:
      - test -d {{.ROOT_DIR}}/{{.SOURCE_DIR}}/deck

  tools-pdfdeck:
    desc: Build pdfdeck from .src
    dir: "{{.ROOT_DIR}}/{{.SOURCE_DIR}}/deck/cmd/pdfdeck"
    cmds:
      - mkdir -p {{.ROOT_DIR}}/{{.BUILD_DIR}}/deck
      - go build -o {{.ROOT_DIR}}/{{.BUILD_DIR}}/deck/pdfdeck .
    status:
      - test -f {{.ROOT_DIR}}/{{.BUILD_DIR}}/deck/pdfdeck
    preconditions:
      - test -d {{.ROOT_DIR}}/{{.SOURCE_DIR}}/deck

  all:
    desc: Build all targets
    cmds:
      - task: tools
      - task: cloudflare
      - task: wasi
      - task: host
